#!/usr/bin/env bash
# render-env.sh — write a node's .env from the canonical key set (F.32 Track 1).
#
# ONE source of truth for a click-processor node's runtime env, used by BOTH
# provisioning paths (admin-panel cloud-init + tds-deploy) so a freshly-created
# node and a tds-deploy node carry an IDENTICAL .env shape. Before F.32 the two
# paths wrote DIFFERENT key sets (cloud-init lacked TDS_CENTRAL_API_KEY;
# tds-deploy lacked TDS_SMOKE_PROBE_SECRET / diag toggles) → silent drift.
#
# PROVISION-TIME ONLY. update.sh deliberately does NOT call this — the rendered
# .env (which holds per-node secrets that are not re-derivable on the node) is
# PRESERVED across code updates. Regenerate only by re-provisioning.
#
# Inputs via environment (caller exports them); writes ".env" into $1 (default cwd).
set -euo pipefail

ENV_DIR="${1:-$(pwd)}"
ENV_FILE="$ENV_DIR/.env"

require() { [ -n "${!1:-}" ] || { echo "render-env: missing required \$$1" >&2; exit 1; }; }
require TDS_NODE_ID
require TDS_NODE_REGION
require TDS_SECRET_KEY
require TDS_CENTRAL_URL
require TDS_CENTRAL_API_KEY

env_name="${TDS_ENVIRONMENT:-production}"

# Fail loud here (actionable) instead of letting the container's F.29 boot guard
# (config.py `_enforce_central_url_presence`) reject a non-https central_url.
case "$env_name" in
  local|development|test) : ;;  # http acceptable for localhost dev
  *)
    case "$TDS_CENTRAL_URL" in
      https://*) : ;;
      *) echo "render-env: TDS_CENTRAL_URL must be https:// in env '$env_name' (got '$TDS_CENTRAL_URL'). F.32 Track 0: point it at the Cloudflare-proxied api-collector host." >&2; exit 1 ;;
    esac ;;
esac

# Code-version stamp → surfaces in /health for drift detection. Caller may pass
# TDS_CODE_VERSION; else derive from the checkout's git HEAD; else 'unknown'.
code_version="${TDS_CODE_VERSION:-}"
if [ -z "$code_version" ]; then
  code_version="$(git -C "$ENV_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
fi

# Q5 (F.32, CORRECTED Track 2): the shipper's X-Node-Key MUST equal the
# collector's `collector_api_key` (TDS_COLLECTOR_API_KEY on the collector) — a
# SHARED deployment secret, NOT the node's `secret_key`. The old default
# `${TDS_CENTRAL_API_KEY:-$TDS_SECRET_KEY}` produced the node secret_key, which
# the collector rejects with 403 "Invalid node key" → shipper fails closed →
# backlog stockpiles (the exact AU/CA symptom). Now REQUIRED (see `require`
# above) — the caller (cloud-init / tds-deploy) MUST pass the collector key.
central_api_key="${TDS_CENTRAL_API_KEY}"

umask 077  # .env holds secrets — owner-only perms
cat > "$ENV_FILE" <<EOF
# Generated by render-env.sh (F.32) — DO NOT commit, DO NOT hand-edit secrets.
# Provision-time only; PRESERVED across code updates. Regenerate via re-provision.
TDS_NODE_ID=${TDS_NODE_ID}
TDS_NODE_REGION=${TDS_NODE_REGION}
TDS_ENVIRONMENT=${env_name}
TDS_PORT=${TDS_PORT:-8100}
CADDY_DOMAIN=${CADDY_DOMAIN:-localhost}
TDS_SECRET_KEY=${TDS_SECRET_KEY}
# Double-write: pydantic env_prefix="TDS_" + field `tds_secret_key` reads
# TDS_TDS_SECRET_KEY (not TDS_SECRET_KEY). Both written so the boot guard finds it.
TDS_TDS_SECRET_KEY=${TDS_SECRET_KEY}
TDS_CENTRAL_URL=${TDS_CENTRAL_URL}
TDS_CENTRAL_API_KEY=${central_api_key}
# F.32 Track 2 — admin-api host for the config-snapshot pull (separate from
# TDS_CENTRAL_URL=collector). Empty ⇒ pull disabled (push-only). Set to the
# admin-api (e.g. https://api-tds.<base>) to enable the pull safety net.
TDS_SYNC_URL=${TDS_SYNC_URL:-}
TDS_SMOKE_PROBE_SECRET=${TDS_SMOKE_PROBE_SECRET:-}
TDS_SENTRY_DSN=${TDS_SENTRY_DSN:-}
# F.40 — per-instance Sentry environment tag (= node_id when attached to
# a tenant Sentry account). Optional (NOT in the `require` block) — empty
# ⇒ click-processor falls back to TDS_ENVIRONMENT.
TDS_SENTRY_ENVIRONMENT=${TDS_SENTRY_ENVIRONMENT:-}
TDS_DIAG_TRACES_BOOST=${TDS_DIAG_TRACES_BOOST:-false}
TDS_DIAG_OBS_STREAM=${TDS_DIAG_OBS_STREAM:-false}
TDS_DIAG_VERBOSE_LOGS=${TDS_DIAG_VERBOSE_LOGS:-false}
# Returning-users v2 — the per-NODE master enable for the identity resolver +
# segmented routing. The click-processor gates the whole feature on
# (TDS_RETURNING_RESOLVER_ENABLED AND per-company settings.returning); the env
# is the global kill-switch, the per-company gate is the operative per-tenant
# control. Default ON in production so a company that enables the feature in the
# admin panel actually activates it on the edge (the audit found nodes shipped
# without these → resolver inert despite company gate ON). Override to false to
# kill the feature fleet-wide regardless of company settings.
TDS_RETURNING_RESOLVER_ENABLED=${TDS_RETURNING_RESOLVER_ENABLED:-true}
TDS_RETURNING_ROUTING_ENABLED=${TDS_RETURNING_ROUTING_ENABLED:-true}
# Returning-users v2 — the DEDICATED signing key ring for the `_tds_id` identity
# cookie (NOT TDS_SECRET_KEY). Form: `kid:secret,kid:secret`. ALL nodes in a
# fleet MUST carry the SAME ring so a cookie minted on one node verifies on every
# other (cross-node gap-free recognition). The value is a deployment secret
# supplied by the caller (cloud-init exports it from the admin-api config); it is
# NEVER in the public mirror. Empty ⇒ codec disabled ⇒ the node still resolves
# returning users via the legacy _tds_vid path, just without the signed cookie.
TDS_IDENTITY_COOKIE_KEYS=${TDS_IDENTITY_COOKIE_KEYS:-}
TDS_IDENTITY_COOKIE_ACTIVE_KID=${TDS_IDENTITY_COOKIE_ACTIVE_KID:-1}
TDS_CODE_VERSION=${code_version}
EOF

# GTD-R75 / ADR-0055 — capacity auto-config, computed at provision time from
# the droplet size slug (WEB_CONCURRENCY read directly by the Dockerfile CMD,
# no TDS_ prefix; TDS_REDIS_MAX_CONNECTIONS read by config.py's pydantic
# Settings, a plain `int` field with no env_ignore_empty). Unlike the rest of
# this heredoc's `${VAR:-}` empty-string fallbacks (all consumed as plain
# strings/booleans downstream), these two feed one shell int-default
# (`${WEB_CONCURRENCY:-2}`, immune to an empty value) and one pydantic `int`
# field (NOT immune — `TDS_REDIS_MAX_CONNECTIONS=""` in the container env
# raises ValidationError(int_parsing) at Settings() construction = import-time
# crash-loop). So these two lines are APPENDED CONDITIONALLY, mirroring
# cloud-init's own conditional-export convention — ABSENT from .env entirely
# (not present-but-empty) whenever the value wasn't resolved, so click-
# processor's own defaults (Dockerfile's WEB_CONCURRENCY default of 2 /
# config.py's redis_max_connections default of 128) govern unopposed.
if [ -n "${WEB_CONCURRENCY:-}" ]; then
  echo "WEB_CONCURRENCY=${WEB_CONCURRENCY}" >> "$ENV_FILE"
fi
if [ -n "${TDS_REDIS_MAX_CONNECTIONS:-}" ]; then
  echo "TDS_REDIS_MAX_CONNECTIONS=${TDS_REDIS_MAX_CONNECTIONS}" >> "$ENV_FILE"
fi

echo "render-env: wrote $ENV_FILE (node=$TDS_NODE_ID region=$TDS_NODE_REGION version=$code_version)"
