#!/usr/bin/env bash
# render-env.sh — write a node's .env from the canonical key set (F.32 Track 1).
#
# ONE source of truth for a click-processor node's runtime env, used by BOTH
# provisioning paths (admin-panel cloud-init + tds-deploy) so a freshly-created
# node and a tds-deploy node carry an IDENTICAL .env shape. Before F.32 the two
# paths wrote DIFFERENT key sets (cloud-init lacked TDS_CENTRAL_API_KEY;
# tds-deploy lacked TDS_SMOKE_PROBE_SECRET / diag toggles) → silent drift.
#
# PROVISION-TIME ONLY. update.sh deliberately does NOT call this — the rendered
# .env (which holds per-node secrets that are not re-derivable on the node) is
# PRESERVED across code updates. Regenerate only by re-provisioning.
#
# Inputs via environment (caller exports them); writes ".env" into $1 (default cwd).
set -euo pipefail

ENV_DIR="${1:-$(pwd)}"
ENV_FILE="$ENV_DIR/.env"

require() { [ -n "${!1:-}" ] || { echo "render-env: missing required \$$1" >&2; exit 1; }; }
require TDS_NODE_ID
require TDS_NODE_REGION
require TDS_SECRET_KEY
require TDS_CENTRAL_URL

env_name="${TDS_ENVIRONMENT:-production}"

# Fail loud here (actionable) instead of letting the container's F.29 boot guard
# (config.py `_enforce_central_url_presence`) reject a non-https central_url.
case "$env_name" in
  local|development|test) : ;;  # http acceptable for localhost dev
  *)
    case "$TDS_CENTRAL_URL" in
      https://*) : ;;
      *) echo "render-env: TDS_CENTRAL_URL must be https:// in env '$env_name' (got '$TDS_CENTRAL_URL'). F.32 Track 0: point it at the Cloudflare-proxied api-collector host." >&2; exit 1 ;;
    esac ;;
esac

# Code-version stamp → surfaces in /health for drift detection. Caller may pass
# TDS_CODE_VERSION; else derive from the checkout's git HEAD; else 'unknown'.
code_version="${TDS_CODE_VERSION:-}"
if [ -z "$code_version" ]; then
  code_version="$(git -C "$ENV_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
fi

# Q5 (F.32): the collector auth value == the shared secret_key (the X-TDS-Key the
# shipper presents). Matches the existing tds-deploy parity. Override via env.
central_api_key="${TDS_CENTRAL_API_KEY:-$TDS_SECRET_KEY}"

umask 077  # .env holds secrets — owner-only perms
cat > "$ENV_FILE" <<EOF
# Generated by render-env.sh (F.32) — DO NOT commit, DO NOT hand-edit secrets.
# Provision-time only; PRESERVED across code updates. Regenerate via re-provision.
TDS_NODE_ID=${TDS_NODE_ID}
TDS_NODE_REGION=${TDS_NODE_REGION}
TDS_ENVIRONMENT=${env_name}
TDS_PORT=${TDS_PORT:-8100}
CADDY_DOMAIN=${CADDY_DOMAIN:-localhost}
TDS_SECRET_KEY=${TDS_SECRET_KEY}
TDS_TDS_SECRET_KEY=${TDS_SECRET_KEY}
TDS_CENTRAL_URL=${TDS_CENTRAL_URL}
TDS_CENTRAL_API_KEY=${central_api_key}
TDS_SMOKE_PROBE_SECRET=${TDS_SMOKE_PROBE_SECRET:-}
TDS_SENTRY_DSN=${TDS_SENTRY_DSN:-}
TDS_DIAG_TRACES_BOOST=${TDS_DIAG_TRACES_BOOST:-false}
TDS_DIAG_OBS_STREAM=${TDS_DIAG_OBS_STREAM:-false}
TDS_DIAG_VERBOSE_LOGS=${TDS_DIAG_VERBOSE_LOGS:-false}
TDS_CODE_VERSION=${code_version}
EOF
echo "render-env: wrote $ENV_FILE (node=$TDS_NODE_ID region=$TDS_NODE_REGION version=$code_version)"
