"""The CONSUMER half of the wall-record seam: `select_wall` reads what the builder writes.

🔴 THIS IS THE TEST THE WHOLE PROGRAMME HAS BEEN MISSING, and its value comes entirely from
where the input comes from.

Every wall test written so far — on both sides — builds its own fixture. `34-G4-WALL-SELECTION.md`
§2.4 names why that is not enough, and this run has already paid for it once (the A27 ordering
defect, where every test built its wall with a ROUTING `action_type` and so exercised a branch
the real row could not reach):

    "a fixture written in the same wrong shape as the loader agrees with itself perfectly"

So the records below are NOT written here. They are loaded from
`offerwall_wall_record_golden.json`, generated by the REAL admin-api sync builder and pinned
on that side by `test_wall_record_golden_is_what_the_builder_emits.py`. Change the builder
and this test either still passes — proving the contract held — or goes red, which is the
only honest way to learn that the seam moved.

THE THREE CONTRACTS THAT FAIL SILENTLY (§2.4), and why a real record is the only proof:

  is_default   `_winner_sort_key` compares `== "1"`. A native `True` reads as NOT default,
               so a default WINS instead of losing.
  campaign_id  `_split_by_binding` reads `== "0"` for global. `None` makes a global wall
               read as campaign-bound and INVERTS the precedence (§2.1).
  criteria     the loader reads `criteria`; a record carrying admin-api's `filters` name
               yields the `"[]"` default -> MATCH-ALL, so a targeted wall serves everyone.

None of those raises. Each produces a plausible wrong answer, which is why "it ran" proves
nothing here and the record's PROVENANCE is the whole test.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.cascade import _split_by_binding
from app.offerwall import select_wall

_VENDORED = Path(__file__).resolve().parent.parent / "fixtures" / \
    "offerwall_wall_record_golden.json"
_CANONICAL = Path(__file__).resolve().parents[4] / "docs" / "design" / \
    "offerwall_wall_record_golden.json"

_GOLDEN = json.loads(_VENDORED.read_text())["vectors"]

_LEVELS = {"buyer": 42, "custom_group": None, "team": None,
           "department": None, "company": 7}


def _record(case: str) -> dict:
    """A builder-produced record, with the `_id` the node's loader adds on read.

    `_load_flow_records` stamps `_id` after HGETALL (`cascade.py`), so a record reaching
    the picker always has it. Adding it here is faithful to the read path, not a fixture
    liberty — and it is the ONLY thing added."""
    v = _GOLDEN[case]
    return {**v["record"], "_id": str(v["flow_id"])}


class TestABuilderProducedWallIsSelectable:
    def test_a_campaign_bound_wall_is_selected(self):
        """The end-to-end claim in one line: what admin-api writes, click-processor picks."""
        assert select_wall([_record("campaign_bound_wall")], _LEVELS) is not None

    def test_a_global_company_wall_is_selected(self):
        assert select_wall([_record("global_company_wall")], _LEVELS) is not None

    def test_a_global_buyer_wall_is_selected(self):
        assert select_wall([_record("global_buyer_wall")], _LEVELS) is not None

    def test_no_candidates_means_no_wall(self):
        """Calibration. Without it every assertion above is satisfiable by a function that
        returns its first argument."""
        assert select_wall([], _LEVELS) is None


class TestTheThreeWireContractsHOLDOnRealRecords:
    """Each of these is a §2.4 silent failure, checked against a record the BUILDER made."""

    def test_the_binding_split_reads_a_builder_record_correctly(self):
        """`campaign_id` is the discriminator, and it is a STRING sentinel. If the builder
        ever emitted `None` for a global wall, this is where it surfaces — as an inverted
        precedence rather than an error."""
        bound, global_ = _split_by_binding([
            _record("campaign_bound_wall"),
            _record("global_company_wall"),
        ])
        assert [f["_id"] for f in bound] == ["4101"]
        assert [f["_id"] for f in global_] == ["4102"]

    def test_a_bound_wall_BEATS_a_global_one_at_a_deeper_scope(self):
        """§2.1's inversion, driven entirely by builder output. The global wall here is at
        the MORE specific scope (buyer 42 vs company 7), so a picker handed a mixed list
        would choose it — bound-before-global is what must decide instead."""
        winner = select_wall(
            [_record("global_buyer_wall"), _record("campaign_bound_wall")], _LEVELS)
        assert winner is not None
        assert winner["_id"] == "4101", (
            "a campaign-bound wall is a narrower statement of intent than a global one, "
            "even when the global one sits at a deeper scope"
        )

    def test_is_default_is_a_STRING_on_every_builder_record(self):
        """A32 forbids a default wall at write time, so every vector reads "0". The point
        is the TYPE, not the value: `True == "1"` is False, so a native bool would silently
        make a default sort as non-default."""
        for case in _GOLDEN:
            value = _GOLDEN[case]["record"]["is_default"]
            assert value == "0", case
            assert value is not False, case

    def test_criteria_arrives_under_the_name_the_loader_reads(self):
        """The match-all trap. `filters` is admin-api's name for this field; if it ever
        reached the wire under that name, a TARGETED wall would serve everyone."""
        for case in _GOLDEN:
            rec = _GOLDEN[case]["record"]
            assert "criteria" in rec, case
            assert "filters" not in rec, case
        crit = json.loads(_GOLDEN["campaign_bound_wall"]["record"]["criteria"])
        assert crit and crit[0]["values"] == ["UA", "PL"], (
            "the targeting must survive serialisation, not just the key name"
        )


class TestTheRoutingVectorIsNOTTreatedAsAWall:
    """The isolation, from the consumer's side. `select_wall` is given the eligible set by
    its caller, so it cannot itself refuse a routing flow — and that is exactly why the
    boundary has to be proven where it IS enforced."""

    def test_the_routing_record_is_not_in_a_wall_list_in_the_first_place(self):
        """The real defence, restated at this end: the routing flow's id goes to
        `campaign:770:flows`, so a wall reader never receives it. That is a PUBLISHER
        property, and it is what makes `select_wall`'s trust of its input safe."""
        assert list(_GOLDEN["routing_flow_for_comparison"]["lists"]) == \
            ["campaign:770:flows"]
        for case in ("campaign_bound_wall", "global_company_wall", "global_buyer_wall"):
            assert all("walls" in k for k in _GOLDEN[case]["lists"]), case


def test_vendored_matches_canonical():
    """Byte-identity with the canonical file — the same pin `stats-service` uses. Without
    it, this service and admin-api can drift while both stay green against stale copies of
    what they each believe the contract is."""
    assert _VENDORED.read_bytes() == _CANONICAL.read_bytes(), (
        "vendored offerwall_wall_record_golden.json drifted from "
        "docs/design/offerwall_wall_record_golden.json — re-vendor it"
    )
